ersion: '3'
services:
 mage:
    build:
      context: ./mage/
      dockerfile: Dockerfile
    container_name: mage
    command: mage start /home/src/mage/${MAGE_PROJECT_NAME}
    env_file:
      - .env
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
    restart: on-failure:5
